diff a/modules/qwen4_flash_resident_decode_stage/Makefile b/modules/qwen4_flash_resident_decode_stage/Makefile	(rejected hunks)
@@ -24,7 +24,7 @@ QWEN4_FLASH_MODEL_REVISION := f5d08274bafd880402bd16f5e3e6c514136ec06c
 QWEN4_FLASH_CONTRACT_SHA256 := $(shell sha256sum $(CURDIR)/../../model_contracts/qwen4_flash_authoritative.json | awk '{print $$1}')
 MODULE_COMPILE_FLAGS := \
 	-DSPARK_QWEN4_FLASH_MODULE_BUILD=1 \
-	-DSPARK_QWEN4_FLASH_MODEL_MTP_LAYER_COUNT=$(MTP_LAYER_COUNT)u \
+	-DSPARK_LLM_MTP_LAYER_COUNT=$(MTP_LAYER_COUNT)u \
 	-DQWEN4_FLASH_MODEL_REVISION=\"$(QWEN4_FLASH_MODEL_REVISION)\" \
 	-DQWEN4_FLASH_CONTRACT_SHA256=\"$(QWEN4_FLASH_CONTRACT_SHA256)\"
 MODULE_INCLUDE_FLAGS = \
