#ifndef SPARKPIPE_SPARK_RESIDENT_DECODE_STAGE_H
#define SPARKPIPE_SPARK_RESIDENT_DECODE_STAGE_H

#include <stdbool.h>
#include <stdint.h>
#include <stdint.h>

#include "sparkpipe/spark_module_abi.h"
#include "sparkpipe/spark_kv_cache.h"


// Stage utility tier: alignment and rounding, used by machinery and by
// every model module. Header-inline so the module and its model sources
// share one definition with zero link surface.
static inline bool SparkResidentDecodeStagePointerIsAligned(
    const void *pointer,
    uintptr_t required_alignment)
{
    return pointer != 0 &&
        ((uintptr_t)pointer % required_alignment) == 0u;
}

static inline uint64_t SparkResidentDecodeStageDivideRoundUpU64(
    uint64_t value,
    uint64_t divisor)
{
    if (divisor == 0u)
    {
        return 0u;
    }
    return (value + divisor - 1u) / divisor;
}
#include "sparkpipe/spark_stage_plan.h"
#include "sparkpipe/spark_hidden_transport.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SPARK_RESIDENT_DECODE_STAGE_NODE_CONTEXT_ABI_VERSION 30u
#define SPARK_RESIDENT_DECODE_STAGE_MOE_W1_COMPONENT_COUNT \
    SPARK_GLM52_MODEL_MOE_W1_COMPONENT_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_FP8_SCALED_GEMM_OUTPUT_ALIGNMENT 128u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_SCALE_BLOCK \
    SPARK_GLM52_MODEL_FP8_SCALE_BLOCK
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_DEVICE_POINTERS 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_DYNAMIC_SCALES 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_COMPRESSED_MLA_ONLY 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_DEVICE_POINTERS | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_KV_CACHE_CAPABILITY_DYNAMIC_SCALES)
#define SPARK_RESIDENT_DECODE_STAGE_QUERY_LATENT_PROJECTION_DIMENSION \
    SPARK_GLM52_MODEL_QUERY_LATENT_PROJECTION_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_ATTENTION_PROJECTION_DIMENSION \
    SPARK_GLM52_MODEL_ATTENTION_PROJECTION_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_QUERY_ROPE_PROJECTION_DIMENSION \
    SPARK_GLM52_MODEL_QUERY_ROPE_PROJECTION_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_FP8_SCALE_EXTENT(dimension) \
    SPARK_GLM52_MODEL_FP8_SCALE_EXTENT(dimension)
#define SPARK_RESIDENT_DECODE_STAGE_FP8_SCALE_COUNT(rows, columns) \
    SPARK_GLM52_MODEL_FP8_SCALE_COUNT(rows, columns)
#define SPARK_RESIDENT_DECODE_STAGE_MAX_FP8_LINEAR_SCALE_COUNT \
    SPARK_GLM52_MODEL_MAX_FP8_LINEAR_SCALE_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_BLOCK_TOKENS SPARK_GLM52_KV_BLOCK_TOKENS
#define SPARK_RESIDENT_DECODE_STAGE_SELECTED_TOKEN_COUNT \
    SPARK_GLM52_MODEL_DSA_SELECTED_TOKEN_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_SELECTED_BLOCK_COUNT \
    ((SPARK_RESIDENT_DECODE_STAGE_SELECTED_TOKEN_COUNT + \
      SPARK_RESIDENT_DECODE_STAGE_BLOCK_TOKENS - 1u) / \
     SPARK_RESIDENT_DECODE_STAGE_BLOCK_TOKENS)
#define SPARK_RESIDENT_DECODE_STAGE_DSA_SCORE_TILE_ROWS 16u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_HEAD_COUNT \
    SPARK_GLM52_MODEL_DSA_INDEX_HEAD_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_HEAD_DIMENSION \
    SPARK_GLM52_MODEL_DSA_INDEX_HEAD_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_QUERY_DIMENSION \
    SPARK_GLM52_MODEL_DSA_INDEX_QUERY_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_KEY_DIMENSION \
    SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_HEAD_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_WEIGHT_DIMENSION \
    SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_HEAD_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_DSA_INDEX_ROPE_DIMENSION \
    SPARK_GLM52_RESIDENT_DECODE_STAGE_ROPE_DIMENSION
#define SPARK_RESIDENT_DECODE_STAGE_RESTRICTED_VOCAB_COUNT \
    SPARK_GLM52_MODEL_RESTRICTED_VOCAB_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_OUTPUT_VOCAB_COUNT \
    SPARK_GLM52_MODEL_OUTPUT_VOCAB_COUNT
#define SPARK_RESIDENT_DECODE_STAGE_HIDDEN_BF16_BYTES \
    SPARK_GLM52_MODEL_HIDDEN_BF16_BYTES
#define SPARK_RESIDENT_DECODE_STAGE_SELECTED_INDEX_BYTES \
    SPARK_GLM52_MODEL_DSA_SELECTED_INDEX_BYTES
#define SPARK_RESIDENT_DECODE_STAGE_MTP_DRAFT_TOKEN_COUNT \
    SPARK_RESIDENT_DECODE_STAGE_MTP_MAX_DRAFT_TOKENS
#define SPARK_RESIDENT_DECODE_STAGE_MAX_SPECULATIVE_ROWS_PER_LANE \
    SPARK_GLM52_MODEL_MAX_SPECULATIVE_ROWS_PER_LANE
#define SPARK_RESIDENT_DECODE_STAGE_MXFP4_GROUP_SIZE \
    SPARK_GLM52_MODEL_MXFP4_GROUP_SIZE
#define SPARK_RESIDENT_DECODE_STAGE_NVFP4_GROUP_SIZE \
    SPARK_GLM52_MODEL_NVFP4_GROUP_SIZE
#define SPARK_RESIDENT_DECODE_STAGE_PHASE_CLOCK_COUNT 16u
#define SPARK_RESIDENT_DECODE_STAGE_LINEAR_PLAN_COUNT 21u
#define SPARK_RESIDENT_DECODE_STAGE_LINEAR_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_QUANTIZED_LINEAR_VIEW_ABI_VERSION 2u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_DISPATCH_PLAN_ABI_VERSION 2u
#define SPARK_RESIDENT_DECODE_STAGE_RESTRICTED_LOGITS_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_MTP_DRAFT_PLAN_ABI_VERSION 2u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_EXACT_STAGE_SLICE_PLAN_ABI_VERSION 4u
#define SPARK_RESIDENT_DECODE_STAGE_PAGED_PREFILL_PLAN_ABI_VERSION 3u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_PLAN_ABI_VERSION 2u
#define SPARK_RESIDENT_DECODE_STAGE_MTP_EVENT_COUNTER_COUNT 5u
#define SPARK_RESIDENT_DECODE_STAGE_FINAL_EPILOGUE_CANDIDATE_GROUP_SIZE 32u
#define SPARK_RESIDENT_DECODE_STAGE_FINAL_EPILOGUE_CANDIDATE_GROUP_COUNT \
    ((SPARK_RESIDENT_DECODE_STAGE_OUTPUT_VOCAB_COUNT + \
      SPARK_RESIDENT_DECODE_STAGE_FINAL_EPILOGUE_CANDIDATE_GROUP_SIZE - 1u) / \
     SPARK_RESIDENT_DECODE_STAGE_FINAL_EPILOGUE_CANDIDATE_GROUP_SIZE)
#define SPARK_RESIDENT_DECODE_STAGE_MAX_PIPELINE_SLOT_COUNT \
    SPARK_STAGE_PLAN_MAX_BATCH_BUCKET
#define SPARK_RESIDENT_DECODE_STAGE_MAX_EXECUTION_ROW_COUNT \
    (SPARK_RESIDENT_DECODE_STAGE_MAX_PIPELINE_SLOT_COUNT * \
     (SPARK_GLM52_MODEL_DSPARK_MAX_SPECULATIVE_TOKEN_COUNT + 1u))
#define SPARK_RESIDENT_DECODE_STAGE_FIRST_ROUTED_LAYER \
    SPARK_GLM52_MODEL_FIRST_ROUTED_LAYER
#define SPARK_RESIDENT_DECODE_STAGE_MAX_ROUTED_STAGE_SLICE_LAYER_COUNT \
    SPARK_STAGE_PLAN_MAX_ROUTED_LAYERS_PER_STAGE
#define SPARK_RESIDENT_DECODE_STAGE_MAX_STAGE_SLICE_LAYER_COUNT \
    (SPARK_RESIDENT_DECODE_STAGE_FIRST_ROUTED_LAYER + \
     SPARK_RESIDENT_DECODE_STAGE_MAX_ROUTED_STAGE_SLICE_LAYER_COUNT)
#define SPARK_RESIDENT_DECODE_STAGE_PAGED_PREFILL_QUERY_TILE_TOKENS 16u
#define SPARK_RESIDENT_DECODE_STAGE_PAGED_PREFILL_KEY_TILE_TOKENS 16u
#define SPARK_RESIDENT_DECODE_STAGE_MTP_GRAPH_VARIANT_COUNT \
    ((SPARK_RESIDENT_DECODE_STAGE_MTP_DRAFT_TOKEN_COUNT * 2u) + 1u)
// THE LIVE-GRAPH BOUND, batch bucket times MTP draft variant. Runtime
// batch-variant selection maps every microbatch to the tightest power-of-2
// bucket in B1..B1024 - eleven compiled variants - and a node's batch drifts
// across the whole ladder as load changes, so one pipeline slot can have
// every bucket's graph times every draft variant live at once. Sizing to
// only the draft variants evicts a warm bucket graph the next step would
// replay, and one recapture is the multi-thousand-launch host cost the graph
// cache exists to remove. The spare arrays grow to hold the bound, which is
// what slot-state ABI version 4 records.
#define SPARK_RESIDENT_DECODE_STAGE_GRAPH_BATCH_VARIANT_BUCKET_COUNT 11u
#define SPARK_RESIDENT_DECODE_STAGE_CUDA_GRAPH_SPARE_ENTRY_COUNT \
    ((SPARK_RESIDENT_DECODE_STAGE_GRAPH_BATCH_VARIANT_BUCKET_COUNT * \
      SPARK_RESIDENT_DECODE_STAGE_MTP_GRAPH_VARIANT_COUNT) - 1u)
#define SPARK_RESIDENT_DECODE_STAGE_CUDA_SLOT_STATE_ABI_VERSION 4u
#define SPARK_RESIDENT_DECODE_STAGE_SLICE_NODE_CONTEXT_ABI_VERSION 3u
#define SPARK_RESIDENT_DECODE_STAGE_PIPELINE_SLOT_SCALAR_INDEX 0u
#define SPARK_RESIDENT_DECODE_STAGE_INVALID_TOKEN_ID UINT32_MAX
#define SPARK_RESIDENT_DECODE_STAGE_CANCELLED_TOKEN_ID UINT32_MAX

#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_PREBOUND_PROJECTIONS 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_TILED_ONLINE_ATTENTION 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_GRAPH_REPLAY 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_PRESELECTED_SPARSE_INDICES 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MLP 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_RESTRICTED_LOGITS 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_FORBID_DEBUG_SYNCHRONIZATION 0x00000040u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FIXED_ACTIVE_BATCH 0x00000080u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_VALIDATED_LATENCY 0x00000100u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MTP_DRAFT 0x00000200u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FULL_STAGE_PLAN 0x00000400u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_TENSOR_CORE_ALIGNMENT 0x00000800u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_NVFP4_ROUTE_SLOT_CACHE 0x00001000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MOE_ROUTER 0x00002000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_OUTPUT_HIDDEN_ONLY 0x00004000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_BULK_PREFILL 0x00008000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_STAGE_SLICE_PLAN 0x00010000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_MODEL_QUANTIZATION 0x00020000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_RUNTIME_KV_BLOCK_TABLE 0x00040000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_HIDDEN_TRANSPORT_INPUT 0x00080000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_HIDDEN_TRANSPORT_OUTPUT 0x00100000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FP8_KV_CACHE 0x00200000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_DSA_KV_FRAGMENT_TRANSPORT 0x00400000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_DSA_SPARSE_PREFILL 0x01000000u
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_PERSISTENT_HIDDEN_TRANSPORT \
    (SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_HIDDEN_TRANSPORT_INPUT | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_HIDDEN_TRANSPORT_OUTPUT)
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_COMPONENT_FAST_PATH \
    (SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_PREBOUND_PROJECTIONS | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_TILED_ONLINE_ATTENTION | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_GRAPH_REPLAY | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_PRESELECTED_SPARSE_INDICES | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MLP | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_RESTRICTED_LOGITS | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_FORBID_DEBUG_SYNCHRONIZATION | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FIXED_ACTIVE_BATCH | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MTP_DRAFT | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_TENSOR_CORE_ALIGNMENT | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MOE_ROUTER)
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FUSED_STAGE_FAST_PATH \
    (SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FULL_STAGE_PLAN | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_FORBID_DEBUG_SYNCHRONIZATION | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FIXED_ACTIVE_BATCH | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_TENSOR_CORE_ALIGNMENT)
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_SOTA_FAST_PATH \
    SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FUSED_STAGE_FAST_PATH
#define SPARK_RESIDENT_DECODE_STAGE_EXECUTION_KNOWN_FLAGS \
    (SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_COMPONENT_FAST_PATH | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FULL_STAGE_PLAN | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_NVFP4_ROUTE_SLOT_CACHE | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FAST_MOE_ROUTER | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_OUTPUT_HIDDEN_ONLY | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_BULK_PREFILL | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_STAGE_SLICE_PLAN | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_MODEL_QUANTIZATION | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_RUNTIME_KV_BLOCK_TABLE | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_HIDDEN_TRANSPORT_INPUT | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_HIDDEN_TRANSPORT_OUTPUT | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_FP8_KV_CACHE | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_REQUIRE_DSA_KV_FRAGMENT_TRANSPORT | \
     SPARK_RESIDENT_DECODE_STAGE_EXECUTION_DSA_SPARSE_PREFILL)

#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_CUDA_GRAPH_REPLAY 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_TENSOR_CORE_PROJECTIONS 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_TILED_ONLINE_ATTENTION 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FUSED_ROPE_KV_WRITE 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FUSED_MOE 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FAST_RESTRICTED_LOGITS 0x00000040u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FAST_MTP_DRAFT 0x00000080u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_ZERO_HOST_STAGING 0x00000100u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_ZERO_DEVICE_MEMCPY 0x00000200u
#define SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_SOTA_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_CUDA_GRAPH_REPLAY | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_TENSOR_CORE_PROJECTIONS | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_TILED_ONLINE_ATTENTION | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FUSED_ROPE_KV_WRITE | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FUSED_MOE | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FAST_RESTRICTED_LOGITS | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_FAST_MTP_DRAFT | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_ZERO_HOST_STAGING | \
     SPARK_RESIDENT_DECODE_STAGE_FULL_STAGE_CAPABILITY_ZERO_DEVICE_MEMCPY)

#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_CUDA_GRAPH_REPLAY 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_TENSOR_CORE_PROJECTIONS 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_TILED_ONLINE_ATTENTION 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FUSED_LAYER_PROGRESS 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FAST_RESTRICTED_LOGITS 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FAST_MTP_DRAFT 0x00000040u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_ZERO_HOST_STAGING 0x00000080u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_ZERO_DEVICE_MEMCPY 0x00000100u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_DEVICE_HIDDEN_HANDOFF 0x00000200u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_QKV_BRANCH_OVERLAP 0x00000400u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_EXACT_RING_FIXED6 0x00000800u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_VLLM_PAGED_PREFILL 0x00001000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_INTERNAL_CUDA_GRAPH_COUNTERS 0x00002000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_AOT_STAGE_LAUNCH 0x00004000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FUSED_STAGE_MOE 0x00008000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FUSED_FINAL_TOKEN_TAIL 0x00010000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_BUILTIN_EXACT_RING_AOT 0x00020000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_BUILTIN_FUSED_STAGE_MOE 0x00040000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_BUILTIN_FUSED_FINAL_TOKEN_EPILOGUE 0x00080000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_LAYER_MAJOR_SPECULATIVE_VERIFY 0x00100000u
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_CUDA_GRAPH_REPLAY | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_TENSOR_CORE_PROJECTIONS | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_TILED_ONLINE_ATTENTION | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FUSED_LAYER_PROGRESS | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_ZERO_HOST_STAGING | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_ZERO_DEVICE_MEMCPY)
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_EXACT_RING_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_REQUIRED_CAPABILITIES | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_DEVICE_HIDDEN_HANDOFF | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_EXACT_RING_FIXED6 | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_INTERNAL_CUDA_GRAPH_COUNTERS)
#define SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_PRODUCTION_RING_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_EXACT_RING_CAPABILITIES | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_AOT_STAGE_LAUNCH | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_QKV_BRANCH_OVERLAP | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FUSED_STAGE_MOE | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_BUILTIN_EXACT_RING_AOT | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_BUILTIN_FUSED_STAGE_MOE | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_FUSED_FINAL_TOKEN_TAIL | \
     SPARK_RESIDENT_DECODE_STAGE_STAGE_SLICE_CAPABILITY_BUILTIN_FUSED_FINAL_TOKEN_EPILOGUE)

#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_TENSOR_CORE_PROJECTIONS 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_BLOCK_KV_WRITE 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_TILED_ATTENTION 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_ZERO_HOST_STAGING 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_ZERO_DEVICE_MEMCPY 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_PAGED_BLOCK_TABLE 0x00000040u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_CHUNKED_PROMPT 0x00000080u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_PREFIX_CACHE 0x00000100u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_PAGED_ATTENTION 0x00000200u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_RUNTIME_KV_TABLE 0x00000400u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_VARIABLE_PROMPT_LENGTHS 0x00000800u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_RUNTIME_PREFILL_VIEW 0x00001000u
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_TENSOR_CORE_PROJECTIONS | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_BLOCK_KV_WRITE | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_TILED_ATTENTION | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_ZERO_HOST_STAGING | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_ZERO_DEVICE_MEMCPY)
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_PAGED_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_REQUIRED_CAPABILITIES | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_PAGED_BLOCK_TABLE | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_CHUNKED_PROMPT)
#define SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_PAGED_ATTENTION_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_PAGED_REQUIRED_CAPABILITIES | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_PREFIX_CACHE | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_PAGED_ATTENTION | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_RUNTIME_KV_TABLE | \
     SPARK_RESIDENT_DECODE_STAGE_BULK_PREFILL_CAPABILITY_VARIABLE_PROMPT_LENGTHS)

#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_DISPATCH_PLAN_KIND_FLASHINFER_B12X 1u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_FUSED_EXPERTS 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_FUSED_TOPK_REDUCE 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_IN_KERNEL_INPUT_QUANT 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_ZERO_HOST_STAGING 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_ZERO_DEVICE_MEMCPY 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_FUSED_EXPERTS | \
     SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_FUSED_TOPK_REDUCE | \
     SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_IN_KERNEL_INPUT_QUANT | \
     SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_ZERO_HOST_STAGING | \
     SPARK_RESIDENT_DECODE_STAGE_B12X_MOE_CAPABILITY_ZERO_DEVICE_MEMCPY)

#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_FUSED_EXPERTS 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_FUSED_TOPK_REDUCE 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_TENSOR_CORE 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_ZERO_HOST_STAGING 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_ZERO_DEVICE_MEMCPY 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_FUSED_EXPERTS | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_FUSED_TOPK_REDUCE | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_TENSOR_CORE | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_ZERO_HOST_STAGING | \
     SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_CAPABILITY_ZERO_DEVICE_MEMCPY)
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_GATE_UP_ORDER_UP_GATE 1u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_WEIGHT_LAYOUT_EXPERT_MAJOR_ROW_MAJOR 1u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_SCALE_LAYOUT_EXPERT_MAJOR_ROW_BLOCK_MAJOR 1u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_QUANT_MODE_E4M3 2u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_SCALE_BLOCK_SIZE \
    SPARK_GLM52_MODEL_FP8_SCALE_BLOCK
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_WEIGHT_ALIGNMENT_BYTES 16u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_SCALE_ALIGNMENT_BYTES 4u
#define SPARK_RESIDENT_DECODE_STAGE_FP8_MOE_WORKSPACE_ALIGNMENT_BYTES 256u



#define SPARK_RESIDENT_DECODE_STAGE_PREFILL_FRAME_VIEW_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_PREFILL_FRAME_VIEW_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkResidentDecodeStagePrefillFrameView))

typedef struct SparkResidentDecodeStagePrefillFrameView
{
    uint32_t abi_version;
    uint32_t descriptor_bytes;
    uint32_t active_sequence_count;
    uint32_t prompt_token_offset;
    uint32_t prompt_token_count;
    uint32_t prompt_token_stride;
    uint32_t hidden_dimension;
    uint32_t reserved0;
    const uint32_t *prompt_positions;
    const uint32_t *prompt_slot_mapping;
    const uint32_t *prompt_context_lengths;
    const uint32_t *prompt_first_block_token_offsets;
    const uint32_t *prompt_token_counts;
    const void *prompt_hidden_bf16;
    const void *prompt_query_latent_bf16;
    const void *prompt_rotated_query_rope_bf16;
    void *prompt_attention_output_latent_bf16;
    void *prompt_output_hidden_bf16;
} SparkResidentDecodeStagePrefillFrameView;

#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_ABI_VERSION 8u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkResidentDecodeStageFrameContext))
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_KV_BLOCK_TABLE \
    0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_TRANSPORT \
    0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_OUTPUT_TRANSPORT \
    0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MODEL_HIDDEN_TAPS \
    0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_PREFILL_VIEW \
    0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MTP_DRAFT_BUDGETS \
    0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_PREFILL_FRAME \
    0x00000040u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_LAYER_MAJOR_SPECULATIVE_VERIFY \
    0x00000080u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MTP_TREE_VERIFY \
    0x00000100u
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_PRERECEIVED \
    0x00000200u
#define SPARK_RESIDENT_DECODE_STAGE_TRANSPORT_SIDEBAND_INDEXSHARE_SELECTED_TOKENS \
    SPARK_HIDDEN_TRANSPORT_SIDEBAND_KIND_INDEXSHARE_SELECTED_TOKENS
#define SPARK_RESIDENT_DECODE_STAGE_TRANSPORT_SIDEBAND_DSPARK_HIDDEN_TAP \
    SPARK_HIDDEN_TRANSPORT_SIDEBAND_KIND_DSPARK_HIDDEN_TAP
#define SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_KNOWN_FLAGS \
    (SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_KV_BLOCK_TABLE | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_TRANSPORT | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_OUTPUT_TRANSPORT | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MODEL_HIDDEN_TAPS | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_PREFILL_VIEW | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MTP_DRAFT_BUDGETS | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_PREFILL_FRAME | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_LAYER_MAJOR_SPECULATIVE_VERIFY | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_MTP_TREE_VERIFY | \
     SPARK_RESIDENT_DECODE_STAGE_FRAME_CONTEXT_FLAG_HIDDEN_INPUT_PRERECEIVED)

typedef SparkStatus (*SparkResidentDecodeStageHiddenTransportPostReceiveSessionFunction)(
    SparkHiddenTransportSession *transport_session,
    SparkHiddenTransportPacket *packet);
typedef SparkStatus (*SparkResidentDecodeStageHiddenTransportSendSessionFunction)(
    SparkHiddenTransportSession *transport_session,
    const SparkHiddenTransportPacket *packet);

#define SPARK_STAGE_MODEL_MAX_HIDDEN_TAPS 5u
#define SPARK_RESIDENT_DECODE_STAGE_MTP_MAX_DRAFT_TOKENS 8u

typedef struct SparkResidentDecodeStageFrameContext
{
    uint32_t abi_version;
    uint32_t descriptor_bytes;
    uint32_t flags;
    uint32_t reserved;
    uint32_t logical_lane_count;
    uint32_t rows_per_lane;
    const SparkKvBlockTableView *kv_block_table;
    const SparkResidentDecodeStagePrefillFrameView *prefill_view;
    const uint32_t *mtp_draft_token_budgets;
    // Opaque model hidden-tap wiring: the drafter module owns the plan
    // type and asserts the tap-count mirror.
    const void *model_hidden_tap_plan;
    void *model_hidden_tap_output_bf16[SPARK_STAGE_MODEL_MAX_HIDDEN_TAPS];
    uint64_t model_hidden_tap_lane_stride_bytes;
    SparkHiddenTransportSession *hidden_input_transport_session;
    SparkHiddenTransportSession *hidden_output_transport_session;
    SparkResidentDecodeStageHiddenTransportPostReceiveSessionFunction hidden_input_post_receive_function;
    SparkResidentDecodeStageHiddenTransportSendSessionFunction hidden_output_send_function;
    SparkHiddenTransportPacket hidden_input_packet;
    SparkHiddenTransportPacket hidden_output_packet;
} SparkResidentDecodeStageFrameContext;

typedef enum SparkResidentDecodeStagePhase
{
    SPARK_RESIDENT_DECODE_STAGE_PHASE_SUBMITTED = 0,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_ATTENTION_NORM = 1,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_ATTENTION_PROJECTION = 2,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_DSA_SELECTION = 3,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_ROPE_KV_WRITE = 4,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_MLA_ATTENTION = 5,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_OUTPUT_PROJECTION = 6,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_POST_ATTENTION_NORM = 7,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_LOCAL_MOE = 8,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_RESTRICTED_LOGITS = 9,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_MTP_DRAFT = 10,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_MTP_VERIFY = 11,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_COMPLETION_READY = 12
} SparkResidentDecodeStagePhase;

typedef enum SparkResidentDecodeStageMtpCounter
{
    SPARK_RESIDENT_DECODE_STAGE_MTP_ACCEPTED = 0,
    SPARK_RESIDENT_DECODE_STAGE_MTP_REJECTED = 1,
    SPARK_RESIDENT_DECODE_STAGE_MTP_COMMITTED = 2,
    SPARK_RESIDENT_DECODE_STAGE_MTP_ROLLBACK = 3,
    SPARK_RESIDENT_DECODE_STAGE_MTP_CANCELLED = 4
} SparkResidentDecodeStageMtpCounter;

typedef enum SparkResidentDecodeStageSparseIndexMode
{
    SPARK_RESIDENT_DECODE_STAGE_SPARSE_INDEX_PRESELECTED = 0,
    SPARK_RESIDENT_DECODE_STAGE_SPARSE_INDEX_COPY_CONTEXT_PREFIX = 1,
    SPARK_RESIDENT_DECODE_STAGE_SPARSE_INDEX_DEBUG_SERIAL_TOPK = 2,
    SPARK_RESIDENT_DECODE_STAGE_SPARSE_INDEX_DSA_INDEXSHARE_FULL = 3,
    SPARK_RESIDENT_DECODE_STAGE_SPARSE_INDEX_DSA_INDEXSHARE_SHARED = 4
} SparkResidentDecodeStageSparseIndexMode;



#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PLAN_ABI_VERSION 1u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_MAX_PAYLOADS 8u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_ENABLED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_MLA_LATENT 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_KEY_NOPE 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_VALUE 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_DSA_INDEX_KEY 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_FP8_SCALE 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_PAYLOAD_FLAG_L2_PREFETCH_ONLY 0x00000040u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_STREAM_ORDERED 0x00000001u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_DEVICE_POINTERS 0x00000002u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_SELECTED_BLOCKS 0x00000004u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_DEDUP_BY_EPOCH 0x00000008u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_ASYNC_EVENT_READY 0x00000010u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_READ_ONLY_PREFETCH 0x00000020u
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_DEVICE_POINTERS | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_SELECTED_BLOCKS | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_DEDUP_BY_EPOCH | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_ASYNC_EVENT_READY)
#define SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_READ_ONLY_REQUIRED_CAPABILITIES \
    (SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_STREAM_ORDERED | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_DEVICE_POINTERS | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_SELECTED_BLOCKS | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_ASYNC_EVENT_READY | \
     SPARK_RESIDENT_DECODE_STAGE_DSA_KV_FRAGMENT_TRANSPORT_CAPABILITY_READ_ONLY_PREFETCH)




typedef enum SparkResidentDecodeStageLaunchCheckMode
{
    SPARK_RESIDENT_DECODE_STAGE_LAUNCH_CHECK_NONE = 0,
    SPARK_RESIDENT_DECODE_STAGE_LAUNCH_CHECK_PEEK = 1,
    SPARK_RESIDENT_DECODE_STAGE_LAUNCH_CHECK_SYNC_ON_ERROR = 2
} SparkResidentDecodeStageLaunchCheckMode;

typedef enum SparkResidentDecodeStagePhaseClockMode
{
    SPARK_RESIDENT_DECODE_STAGE_PHASE_CLOCK_DISABLED = 0,
    SPARK_RESIDENT_DECODE_STAGE_PHASE_CLOCK_DEVICE_CLOCK64 = 1
} SparkResidentDecodeStagePhaseClockMode;

typedef enum SparkResidentDecodeStageProjectionMode
{
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_LOWERED_BF16 = 0,
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_RAW_BF16 = 1,
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_RAW_FP8_E4M3 = 2,
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_RAW_NVFP4_E2M1 = 3,
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_RAW_MXFP4_E2M1 = 4
} SparkResidentDecodeStageProjectionMode;

typedef enum SparkResidentDecodeStageLayerProgressionMode
{
    SPARK_RESIDENT_DECODE_STAGE_LAYER_ATTENTION_ONLY = 0,
    SPARK_RESIDENT_DECODE_STAGE_LAYER_DENSE_BF16_MLP = 1,
    SPARK_RESIDENT_DECODE_STAGE_LAYER_ROUTER_BF16_TOPK_ONLY = 2,
    SPARK_RESIDENT_DECODE_STAGE_LAYER_ROUTED_NVFP4_TOPK = 3,
    SPARK_RESIDENT_DECODE_STAGE_LAYER_ROUTED_FP8_TOPK = 4,
    // value 5 retired with w8lut; the hole is deliberate
} SparkResidentDecodeStageLayerProgressionMode;


typedef enum SparkResidentDecodeStageProjectionBackendMode
{
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_BACKEND_INVALID = 0,
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_BACKEND_PREBOUND_CUBLASLT = 1,
    SPARK_RESIDENT_DECODE_STAGE_PROJECTION_BACKEND_PREBOUND_TENSOR_CORE = 2
} SparkResidentDecodeStageProjectionBackendMode;

typedef enum SparkResidentDecodeStageMlpExecutionMode
{
    SPARK_RESIDENT_DECODE_STAGE_MLP_EXECUTION_INVALID = 0,
    SPARK_RESIDENT_DECODE_STAGE_MLP_EXECUTION_PREBOUND_TENSOR_CORE = 1,
    SPARK_RESIDENT_DECODE_STAGE_MLP_EXECUTION_FLASHINFER_B12X_MOE = 2,
    SPARK_RESIDENT_DECODE_STAGE_MLP_EXECUTION_PREBOUND_QUANTIZED_TENSOR_CORE = 3,
    SPARK_RESIDENT_DECODE_STAGE_MLP_EXECUTION_FP8_EXPERT_TENSOR_CORE = 4
    // value 5 retired with w8lut
} SparkResidentDecodeStageMlpExecutionMode;

typedef enum SparkResidentDecodeStageAttentionExecutionMode
{
    SPARK_RESIDENT_DECODE_STAGE_ATTENTION_EXECUTION_INVALID = 0,
    SPARK_RESIDENT_DECODE_STAGE_ATTENTION_EXECUTION_TILED_ONLINE_SOFTMAX = 1,
    SPARK_RESIDENT_DECODE_STAGE_ATTENTION_EXECUTION_ABSORBED_LATENT = 2
} SparkResidentDecodeStageAttentionExecutionMode;




typedef enum SparkResidentDecodeStageModelQuantizationMode
{
    SPARK_RESIDENT_DECODE_STAGE_MODEL_QUANTIZATION_AUTO = 0,
    SPARK_RESIDENT_DECODE_STAGE_MODEL_QUANTIZATION_NVFP4_4BIT = 1,
    SPARK_RESIDENT_DECODE_STAGE_MODEL_QUANTIZATION_FP8_E4M3_8BIT = 2,
    // value 3 retired with w8lut
} SparkResidentDecodeStageModelQuantizationMode;

typedef struct SparkResidentDecodeStageQuantizedLinearView
{
    uint32_t abi_version;
    uint32_t weight_format;
    uint32_t input_dimension;
    uint32_t output_dimension;
    uint32_t storage_output_dimension;
    uint32_t scale_block_size;
    uint32_t output_is_f32;
    uint32_t reserved0;
    const void *weight_payload;
    const void *weight_scale;
    uint64_t weight_payload_bytes;
    uint64_t weight_scale_bytes;
    void *output_workspace;
    uint64_t output_workspace_bytes;
} SparkResidentDecodeStageQuantizedLinearView;

typedef struct SparkResidentDecodeStageLinearPlan
{
    uint32_t abi_version;
    uint32_t plan_kind;
    uint32_t input_dimension;
    uint32_t output_dimension;
    uint32_t maximum_active_sequence_count;
    uint32_t output_is_f32;
    void *cublaslt_handle;
    void *matmul_descriptor;
    void *input_layout;
    void *weight_layout;
    void *output_layout;
    const void *algorithm;
    void *workspace;
    uint64_t workspace_bytes;
    float alpha;
    float beta;
    void *custom_launch_function;
    void *custom_state;
} SparkResidentDecodeStageLinearPlan;




typedef struct SparkResidentDecodeStageFp8KvCachePlan
{
    uint32_t abi_version;
    uint32_t capability_flags;
    uint32_t maximum_active_sequence_count;
    uint32_t cache_token_capacity;
    uint32_t cache_token_elements;
    uint32_t key_nope_elements;
    uint32_t value_elements;
    uint32_t scale_block_size;
    uint8_t *mla_cache_fp8_e4m3;
    float *mla_cache_scale_f32;
    uint8_t *key_nope_cache_fp8_e4m3;
    float *key_nope_cache_scale_f32;
    uint8_t *value_cache_fp8_e4m3;
    float *value_cache_scale_f32;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageFp8KvCachePlan;

typedef struct SparkResidentDecodeStageRestrictedLogitsPlan
{
    uint32_t abi_version;
    uint32_t restricted_vocab_count;
    uint32_t hidden_dimension;
    uint32_t output_is_f32;
    void *launch_function;
    void *opaque_state;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageRestrictedLogitsPlan;


typedef struct SparkResidentDecodeStageMtpDraftPlan
{
    uint32_t abi_version;
    uint32_t restricted_vocab_count;
    uint32_t hidden_dimension;
    uint32_t draft_token_count;
    uint32_t weight_format;
    uint32_t graph_draft_token_count;
    void *launch_function;
    void *opaque_state;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageMtpDraftPlan;

typedef struct SparkResidentDecodeStageFullStagePlan
{
    uint32_t abi_version;
    uint32_t maximum_active_sequence_count;
    uint32_t capability_flags;
    uint32_t reserved;
    void *launch_function;
    void *opaque_state;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageFullStagePlan;


typedef struct SparkResidentDecodeStageStageSlicePlan
{
    uint32_t abi_version;
    uint32_t maximum_active_sequence_count;
    uint32_t maximum_layer_count;
    uint32_t capability_flags;
    void *launch_function;
    void *opaque_state;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageStageSlicePlan;




typedef struct SparkResidentDecodeStageExactStageSlicePlan
{
    uint32_t abi_version;
    uint32_t descriptor_bytes;
    uint32_t stage_index;
    uint32_t first_layer_index;
    uint32_t layer_count;
    uint32_t batch_bucket;
    uint32_t maximum_active_sequence_count;
    uint32_t logical_lane_capacity;
    uint32_t maximum_speculative_rows_per_lane;
    uint32_t final_token_candidate_row_capacity;
    uint32_t capability_flags;
    void *query_branch_stream;
    void *kv_branch_stream;
    void *branch_ready_event;
    void *query_branch_event;
    void *kv_branch_event;
    void *launch_function;
    void *opaque_state;
    void *fused_moe_launch_function;
    void *fused_moe_state;
    void *final_token_launch_function;
    void *final_token_state;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageExactStageSlicePlan;

#define SPARK_RESIDENT_DECODE_STAGE_EXACT_STAGE_SLICE_PLAN_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkResidentDecodeStageExactStageSlicePlan))

typedef struct SparkResidentDecodeStagePagedPrefillPlan
{
    uint32_t abi_version;
    uint32_t descriptor_bytes;
    uint32_t block_token_count;
    uint32_t maximum_prompt_token_count;
    uint32_t maximum_active_sequence_count;
    uint32_t hidden_dimension;
    uint32_t cache_token_elements;
    uint32_t flags;
    const uint32_t *prompt_positions;
    const uint32_t *prompt_slot_mapping;
    const uint32_t *prompt_context_lengths;
    const uint32_t *prompt_first_block_token_offsets;
    const uint32_t *prompt_block_table;
    const void *prompt_hidden_bf16;
    const uint32_t *prompt_token_counts;
    uint32_t prompt_token_stride;
    uint32_t query_tile_token_count;
    uint32_t key_tile_token_count;
    uint32_t reserved0;
    const void *prompt_query_latent_bf16;
    const void *prompt_rotated_query_rope_bf16;
    void *prompt_attention_output_latent_bf16;
    void *prompt_output_hidden_bf16;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStagePagedPrefillPlan;

#define SPARK_RESIDENT_DECODE_STAGE_PAGED_PREFILL_PLAN_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkResidentDecodeStagePagedPrefillPlan))

typedef struct SparkResidentDecodeStageBulkPrefillPlan
{
    uint32_t abi_version;
    uint32_t maximum_active_sequence_count;
    uint32_t maximum_prompt_token_count;
    uint32_t capability_flags;
    void *launch_function;
    void *opaque_state;
    void *workspace;
    uint64_t workspace_bytes;
    uint64_t validated_maximum_latency_ns;
} SparkResidentDecodeStageBulkPrefillPlan;


// Per-pipeline-slot CUDA graph state. Decode steps are captured once per
// (active_sequence_count, specialization_signature) key and replayed
// thereafter; the contract for what may vary between replays - device-side
// buffer contents yes, any host-derived launch input no - and the capture /
// replay / eager-fallback decision live in inference/stage/graph_replay.h,
// which operates these fields. The layout is ABI: the primary entry is the
// named triple, the spares are the parallel arrays, and eviction is LRU by
// last_use epoch against graph_cache_clock. graph_capture_count and
// graph_replay_count are cumulative for the runtime snapshot.
typedef struct SparkResidentDecodeStageCudaPipelineSlotState
{
    uint32_t abi_version;
    uint32_t graph_active_sequence_count;
    void *cuda_graph_exec;
    uint64_t graph_specialization_signature;
    uint64_t graph_capture_count;
    void *cuda_graph_exec_cache[
        SPARK_RESIDENT_DECODE_STAGE_CUDA_GRAPH_SPARE_ENTRY_COUNT];
    uint32_t graph_cache_active_sequence_counts[
        SPARK_RESIDENT_DECODE_STAGE_CUDA_GRAPH_SPARE_ENTRY_COUNT];
    uint64_t graph_cache_specialization_signatures[
        SPARK_RESIDENT_DECODE_STAGE_CUDA_GRAPH_SPARE_ENTRY_COUNT];
    uint64_t graph_cache_last_use_epochs[
        SPARK_RESIDENT_DECODE_STAGE_CUDA_GRAPH_SPARE_ENTRY_COUNT];
    uint64_t graph_cache_clock;
    uint64_t graph_replay_count;
    uint64_t launch_chain_count;
    uint64_t layer_body_success_count;
    uint64_t b12x_moe_success_count;
    uint64_t launch_error_count;
} SparkResidentDecodeStageCudaPipelineSlotState;

typedef struct SparkResidentDecodeStagePipelineSlot
{
    void *cuda_stream;
    const void *input_hidden_bf16;
    void *normalized_hidden_bf16;
    void *query_latent_bf16;
    void *query_rope_input_bf16;
    void *key_rope_input_bf16;
    void *current_kv_latent_bf16;
    void *raw_query_a_bf16;
    void *raw_query_a_normalized_bf16;
    void *raw_query_b_bf16;
    void *raw_kv_a_bf16;
    void *raw_kv_a_normalized_bf16;
    void *raw_kv_b_bf16;
    const uint32_t *positions;
    const uint32_t *slot_mapping;
    const uint32_t *block_table;
    const uint32_t *context_lengths;
    const uint32_t *first_block_token_offsets;
    void *query_index_heads_bf16;
    void *current_key_index_bf16;
    void *index_head_weights_bf16;
    uint32_t dsa_candidate_count;
    uint32_t *sparse_token_indices;
    void *rotated_query_rope_bf16;
    void *attention_output_latent_bf16;
    void *attention_projected_hidden_bf16;
    void *post_attention_hidden_bf16;
    void *post_attention_normalized_hidden_bf16;
    uint32_t *moe_topk_expert_ids;
    float *moe_topk_weights;
    float *moe_router_logits;
    int32_t *moe_bound_expert_slots;
    void *moe_gate_bf16;
    void *moe_up_bf16;
    void *moe_intermediate_bf16;
    void *moe_route_output_bf16;
    void *layer_output_hidden_bf16;
    const void *mtp_draft_hidden_bf16;
    float *restricted_logits;
    float *mtp_draft_logits;
    uint32_t *restricted_selected_token_ids;
    float *restricted_selected_token_scores;
    uint32_t *mtp_draft_token_ids;
    const uint32_t *mtp_draft_token_budgets;
    const uint32_t *mtp_target_token_ids;
    uint32_t *mtp_accept_mask;
    uint32_t *mtp_committed_token_ids;
    uint32_t *mtp_event_counters;
    uint64_t *phase_clock_cycles;
    const uint32_t *mtp_tree_shadow_slot_mapping;
} SparkResidentDecodeStagePipelineSlot;

typedef struct SparkResidentDecodeStageNodeContext
{
    uint32_t abi_version;
    uint32_t pipeline_slot_count;
    uint32_t max_active_sequence_count;
    uint32_t logical_lane_capacity;
    uint32_t cache_token_capacity;
    uint32_t kv_block_count;
    uint32_t max_blocks_per_sequence;
    uint32_t position_count;
    uint32_t dsa_candidate_capacity;
    float qk_scale;
    float rms_norm_epsilon;
    const float *cos_table;
    const float *sin_table;
    void *mla_cache_bf16;
    void *key_nope_cache_bf16;
    void *value_cache_bf16;
    const void *attention_norm_weight_bf16;
    const void *query_latent_weight_bf16;
    const void *query_rope_weight_bf16;
    const void *key_rope_weight_bf16;
    const void *kv_latent_weight_bf16;
    const void *raw_query_a_weight_bf16;
    const void *raw_query_a_norm_weight_bf16;
    const void *raw_query_b_weight_bf16;
    const void *raw_kv_a_weight_bf16;
    const void *raw_kv_a_norm_weight_bf16;
    const void *raw_kv_b_weight_bf16;
    const uint8_t *raw_query_a_weight_fp8_e4m3;
    const float *raw_query_a_weight_scale_inv_f32;
    const uint8_t *raw_query_b_weight_fp8_e4m3;
    const float *raw_query_b_weight_scale_inv_f32;
    const uint8_t *raw_kv_a_weight_fp8_e4m3;
    const float *raw_kv_a_weight_scale_inv_f32;
    const uint8_t *raw_kv_b_weight_fp8_e4m3;
    const float *raw_kv_b_weight_scale_inv_f32;
    const void *attention_output_weight_bf16;
    const uint8_t *attention_output_weight_fp8_e4m3;
    const float *attention_output_weight_scale_inv_f32;
    const void *post_attention_norm_weight_bf16;
    const void *dense_gate_weight_bf16;
    const void *dense_up_weight_bf16;
    const void *dense_down_weight_bf16;
    const uint8_t *dense_gate_weight_fp8_e4m3;
    const float *dense_gate_weight_scale_inv_f32;
    const uint8_t *dense_up_weight_fp8_e4m3;
    const float *dense_up_weight_scale_inv_f32;
    const uint8_t *dense_down_weight_fp8_e4m3;
    const float *dense_down_weight_scale_inv_f32;
    const void *final_norm_weight_bf16;
    const void *restricted_lm_head_weight_bf16;
    const uint8_t *mtp_mxfp4_weight_payload_u8;
    const uint8_t *mtp_mxfp4_scale_e8m0_u8;
    const uint32_t *restricted_token_ids;
    const SparkResidentDecodeStagePipelineSlot *pipeline_slots;
    SparkResidentDecodeStageCudaPipelineSlotState *cuda_pipeline_slot_states;
    uint32_t projection_mode;
    uint32_t layer_progression_mode;
    uint32_t moe_expert_count;
    uint32_t moe_first_bound_expert_id;
    uint32_t moe_bound_expert_count;
    uint32_t moe_top_k;
    uint32_t moe_intermediate_dimension;
    uint32_t dense_intermediate_dimension;
    uint32_t sparse_index_mode;
    uint32_t launch_check_mode;
    uint32_t phase_clock_mode;
    uint32_t enable_cuda_graph_replay;
    uint32_t projection_backend_mode;
    uint32_t mlp_execution_mode;
    uint32_t attention_execution_mode;
    uint32_t reserved_execution_flags;
    const SparkResidentDecodeStageLinearPlan *linear_plans;
    uint32_t linear_plan_count;
    const void *b12x_moe_dispatch_plan;
    const SparkResidentDecodeStageRestrictedLogitsPlan *restricted_logits_plan;
    const SparkResidentDecodeStageMtpDraftPlan *mtp_draft_plan;
    const SparkResidentDecodeStageFullStagePlan *full_stage_plan;
    const SparkResidentDecodeStageBulkPrefillPlan *bulk_prefill_plan;
    const void *fp8_moe_plan;
    const SparkResidentDecodeStageFp8KvCachePlan *fp8_kv_cache_plan;
    uint32_t model_quantization_mode;
    uint32_t reserved1;
    uint64_t validated_stage_latency_ns;
    uint64_t estimated_service_time_ns;
    const void *moe_router_weight_bf16;
    const float *moe_router_score_bias_f32;
    float moe_routed_scaling_factor;
    uint32_t moe_norm_topk_prob;
    uint32_t kv_block_token_count;
    uint32_t layer_index;
    void *device_probe_hash_slots;
    uint32_t dsa_indexshare_source_layer_index;
    uint32_t dsa_indexshare_group_end_layer_exclusive;
    uint32_t dsa_indexshare_selected_token_count;
    uint32_t dsa_indexshare_layer_count;
    uint32_t dsa_index_head_count;
    uint32_t dsa_index_head_dimension;
    uint32_t dsa_score_row_capacity;
    uint32_t *selected_token_indices_by_layer;
    const void *index_query_weight_bf16;
    const void *index_key_weight_bf16;
    const uint8_t *index_query_weight_fp8_e4m3;
    const float *index_query_weight_scale_inv_f32;
    const uint8_t *index_key_weight_fp8_e4m3;
    const float *index_key_weight_scale_inv_f32;
    const void *index_weights_proj_weight_bf16;
    const void *index_key_norm_weight_bf16;
    const void *index_key_norm_bias_bf16;
    float *dsa_score_tiles_f32;
    uint32_t *dsa_prefill_selected_u32;
    uint32_t *dsa_prefill_row_context_lengths_u32;
    uint32_t *dsa_prefill_row_sequences_u32;
    uint32_t *dsa_prefill_row_positions_u32;
    void *dsa_prefill_key_scratch_bf16;
    void *key_index_block_min_bf16;
    void *key_index_block_max_bf16;
    uint8_t *dsa_summary_dirty_flags_u8;
    void *dsa_prefill_query_a_bf16;
    void *dsa_prefill_query_index_heads_bf16;
    void *dsa_prefill_index_weights_bf16;
    void *dsa_prefill_normalized_hidden_bf16;
    void *dsa_prefill_low_scratch_bf16;
    uint32_t dsa_prefill_row_capacity;
    const void *key_index_cache_bf16;
    const float *index_head_weights_f32;
    float index_softmax_scale;
    uint32_t *selected_block_indices_by_layer;
    uint32_t *selected_block_counts_by_layer;
    uint32_t *dsa_selection_epoch_by_layer;
    uint32_t dsa_selected_block_stride;
    uint32_t dsa_selected_block_capacity;
    uint32_t dsa_selected_block_layer_count;
    uint32_t dsa_cache_first_layer_index;
    const void *dsa_kv_fragment_prefetch_plan;
    const void *dsa_kv_fragment_save_plan;
    uint32_t kv_storage_token_capacity;

} SparkResidentDecodeStageNodeContext;

typedef struct SparkResidentDecodeStageSliceNodeContext
{
    uint32_t abi_version;
    uint32_t descriptor_bytes;
    uint32_t first_layer_index;
    uint32_t layer_count;
    uint32_t final_token_stage;
    uint32_t reserved;
    const SparkResidentDecodeStageNodeContext *const *layer_node_contexts;
    const SparkResidentDecodeStageStageSlicePlan *stage_slice_plan;
} SparkResidentDecodeStageSliceNodeContext;

#define SPARK_RESIDENT_DECODE_STAGE_SLICE_NODE_CONTEXT_DESCRIPTOR_BYTES \
    ((uint32_t)sizeof(SparkResidentDecodeStageSliceNodeContext))

SparkStatus SparkResidentDecodeStageInitialize(
    const SparkFirmwareModuleConfiguration *configuration,
    const SparkFirmwareModuleHostServices *host_services,
    void **module_state);

SparkStatus SparkResidentDecodeStageExecute(
    void *module_state,
    SparkModelDriverFrame *frame);

SparkStatus SparkResidentDecodeStageAdmit(
    void *module_state,
    const SparkModelDriverAdmissionRequest *request,
    SparkModelDriverAdmissionDecision *decision);

SparkStatus SparkResidentDecodeStageSnapshot(
    void *module_state,
    uint32_t program_id,
    SparkModelDriverRuntimeSnapshot *snapshot);

void SparkResidentDecodeStageDestroy(void *module_state);

SparkStatus SparkResidentDecodeStageLaunchFlashInferB12xMoe(
    const void *b12x_moe_dispatch_plan,
    const SparkResidentDecodeStageNodeContext *node_context,
    const SparkResidentDecodeStagePipelineSlot *pipeline_slot,
    uint32_t active_sequence_count,
    void *cuda_stream);

SparkStatus SparkResidentDecodeStageLaunchFp8Moe(
    const void *fp8_moe_plan,
    const SparkResidentDecodeStageNodeContext *node_context,
    const SparkResidentDecodeStagePipelineSlot *pipeline_slot,
    uint32_t active_sequence_count,
    void *cuda_stream);

#ifdef __cplusplus
}
#endif

static inline bool SparkResidentDecodeStagePointerIsAligned(
    const void *pointer,
    uintptr_t required_alignment);

static inline bool SparkResidentDecodeStageExecutionFlagIsSet(
    const SparkResidentDecodeStageNodeContext *node_context,
    uint32_t execution_flag)
{
    return (node_context->reserved_execution_flags & execution_flag) != 0u;
}



#endif
